client_config_backend: settings
client_config:
  client_id: <Google_Cloud_API_Client_ID>
  client_secret: <Google_Cloud_API_Secret>

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive
